[package]
name = "issue-1471"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.0"
wasm-bindgen = "0.2.79"

[lib]
crate-type = ["cdylib", "rlib"]
